[package]
name = "complx_app"
version = "0.1.0"
authors = ["MrFixTHhis <mrfixthis55@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"

[dev-dependencies]
pretty_assertions = "1.3.0"
